### ISSUE TITLE
Switch to a stable version of BlobProvider

### ISSUE THREAD

**Issue by sffc** [iainireland/icu4x-js-regexp#1]
I suggest that as soon as 0.3 is stamped upstream, you update your code and data file against that version.  The blob format is still subject to change; for example, we just changed from Bincode to Postcard (https://github.com/unicode-org/icu4x/pull/878), which invalidates previously generated blobs.

**Comment by iainireland** [comment]
Did this a long time ago; forgot to close the issue.
